version: '3.3'

services:
    container-mysql:
        image: mysql:5.7
        restart: always
        volumes:
            - './mysql_data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - MYSQL_DATABASE=apidb
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=supersecret
        ports:
            - '3306:3306'
